//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Happy.Scaffolding.MVC.UI {
    using System;
    
    
    /// <summary>
    ///   一个强类型的资源类，用于查找本地化的字符串等。
    /// </summary>
    // 此类是由 StronglyTypedResourceBuilder
    // 类通过类似于 ResGen 或 Visual Studio 的工具自动生成的。
    // 若要添加或移除成员，请编辑 .ResX 文件，然后重新运行 ResGen
    // (以 /str 作为命令选项)，或重新生成 VS 项目。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class MvcScaffolderDialogResources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal MvcScaffolderDialogResources() {
        }
        
        /// <summary>
        ///   返回此类使用的缓存的 ResourceManager 实例。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Happy.Scaffolding.MVC.UI.MvcScaffolderDialogResources", typeof(MvcScaffolderDialogResources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   使用此强类型资源类，为所有资源查找
        ///   重写当前线程的 CurrentUICulture 属性。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   查找类似 Add 的本地化字符串。
        /// </summary>
        public static string AddButton_Content {
            get {
                return ResourceManager.GetString("AddButton_Content", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Back 的本地化字符串。
        /// </summary>
        public static string BackButton_Content {
            get {
                return ResourceManager.GetString("BackButton_Content", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Cancel 的本地化字符串。
        /// </summary>
        public static string CancelButton_Content {
            get {
                return ResourceManager.GetString("CancelButton_Content", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Confirm and continue. 的本地化字符串。
        /// </summary>
        public static string CheckBox_IsConfirm {
            get {
                return ResourceManager.GetString("CheckBox_IsConfirm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Controller name 的本地化字符串。
        /// </summary>
        public static string ControllerName {
            get {
                return ResourceManager.GetString("ControllerName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Data _context class: 的本地化字符串。
        /// </summary>
        public static string DataContextTypeLabel_Content {
            get {
                return ResourceManager.GetString("DataContextTypeLabel_Content", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Master page placeholder ID: 的本地化字符串。
        /// </summary>
        public static string DesktopContentPlaceholderIdLabel_Content {
            get {
                return ResourceManager.GetString("DesktopContentPlaceholderIdLabel_Content", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Master page: 的本地化字符串。
        /// </summary>
        public static string DesktopViewsLabel_Content {
            get {
                return ResourceManager.GetString("DesktopViewsLabel_Content", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Please select a master page from the list 的本地化字符串。
        /// </summary>
        public static string Error_DesktopMasterPageRequired {
            get {
                return ResourceManager.GetString("Error_DesktopMasterPageRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Please select a model class from the list 的本地化字符串。
        /// </summary>
        public static string Error_ModelTypeRequired {
            get {
                return ResourceManager.GetString("Error_ModelTypeRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Please enter the ID of the placeholder control to place the generated content in 的本地化字符串。
        /// </summary>
        public static string Error_PlaceholderIdRequired {
            get {
                return ResourceManager.GetString("Error_PlaceholderIdRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Set Form Layout Columns   的本地化字符串。
        /// </summary>
        public static string FormViewCols {
            get {
                return ResourceManager.GetString("FormViewCols", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Generate Master-Detail relationship Action and PageView 的本地化字符串。
        /// </summary>
        public static string GenerateMasterDetailRelationship {
            get {
                return ResourceManager.GetString("GenerateMasterDetailRelationship", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Generate views 的本地化字符串。
        /// </summary>
        public static string GenerateViews {
            get {
                return ResourceManager.GetString("GenerateViews", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 (Leave empty if it is set in Razor _viewstart file) 的本地化字符串。
        /// </summary>
        public static string LeaveEmpty {
            get {
                return ResourceManager.GetString("LeaveEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Method name / Store Procedure import function 的本地化字符串。
        /// </summary>
        public static string MethodNameLabel_Content {
            get {
                return ResourceManager.GetString("MethodNameLabel_Content", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Model cla_ss: 的本地化字符串。
        /// </summary>
        public static string ModelTypeLabel_Content {
            get {
                return ResourceManager.GetString("ModelTypeLabel_Content", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Next 的本地化字符串。
        /// </summary>
        public static string NextButton_Content {
            get {
                return ResourceManager.GetString("NextButton_Content", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Over write existing pages 的本地化字符串。
        /// </summary>
        public static string OverwriteCheckBox_Content {
            get {
                return ResourceManager.GetString("OverwriteCheckBox_Content", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Program title 的本地化字符串。
        /// </summary>
        public static string ProgramerNameLabel_Content {
            get {
                return ResourceManager.GetString("ProgramerNameLabel_Content", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Reference script libraries 的本地化字符串。
        /// </summary>
        public static string ReferenceScriptLibraries {
            get {
                return ResourceManager.GetString("ReferenceScriptLibraries", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Add MVC from Store Procedure 的本地化字符串。
        /// </summary>
        public static string SPScaffolderDialog_Title {
            get {
                return ResourceManager.GetString("SPScaffolderDialog_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Query form setting 的本地化字符串。
        /// </summary>
        public static string SPScaffolderDialog_Title2 {
            get {
                return ResourceManager.GetString("SPScaffolderDialog_Title2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Result list column setting 的本地化字符串。
        /// </summary>
        public static string SPScaffolderDialog_Title3 {
            get {
                return ResourceManager.GetString("SPScaffolderDialog_Title3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Add MVC controller and views for C.R.U.D 的本地化字符串。
        /// </summary>
        public static string Title {
            get {
                return ResourceManager.GetString("Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Use async controller actions 的本地化字符串。
        /// </summary>
        public static string UseAsyncControllerActions {
            get {
                return ResourceManager.GetString("UseAsyncControllerActions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Use a layout page 的本地化字符串。
        /// </summary>
        public static string UseLayoutPage {
            get {
                return ResourceManager.GetString("UseLayoutPage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 View prefix 的本地化字符串。
        /// </summary>
        public static string ViewPrefixLabel_Content {
            get {
                return ResourceManager.GetString("ViewPrefixLabel_Content", resourceCulture);
            }
        }
    }
}
